### ISSUE TITLE
[Design] 마이페이지 구현

### ISSUE THREAD

**Issue by DevDAN09** [Soongsil-CoffeeChat/CoffeeChat-Client#5]
ISSUE : ✅DESIGN
============
Description
============
마이페이지 화면 구현입니다.

View
-----

![image](https://github.com/Soongsil-CoffeeChat/CoffeeChat-Client/assets/146945828/828d7985-1ae4-48a0-8a76-e9d21ab9ccf6)

**Comment by candosh** [comment]
@DevDAN09 영민님 아직 이 이슈 할당 유효하신가요?ㅎㅎ🐶

아이폰 XR과 14Pro에서는 잘리네용! 다른 흰색 배경은 문제 없는데 마이페이지는 색깔 변화가 있는 만큼 맞춰줘야 할 것 같아서 ㅎㅎ

[iPone XR]
<img width="400" alt="스크린샷 2024-06-03 오후 4 12 45" src="https://github.com/Soongsil-CoffeeChat/CoffeeChat-Client/assets/104755384/874b7f6e-e282-4a37-aefb-2d2069116197" >

[iPone 14Pro]
<img width="400" alt="스크린샷 2024-06-03 오후 4 11 25" src="https://github.com/Soongsil-CoffeeChat/CoffeeChat-Client/assets/104755384/cff5852e-6a6e-404b-8b0a-50fa4736990e">
